### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by chbergmann** [chbergmann/OpticsWorkbench#10]
When I open a file with optic elements I get:

[code]08:29:19  Traceback (most recent call last):
  File "/home/mac/.FreeCAD/Mod/OpticsWorkbench/Ray.py", line 53, in onChanged
    self.redrawRay(fp)
  File "/home/mac/.FreeCAD/Mod/OpticsWorkbench/Ray.py", line 85, in redrawRay
    insiders = self.isInsideLens(ray.Vertexes[0])
  File "/home/mac/.FreeCAD/Mod/OpticsWorkbench/Ray.py", line 271, in isInsideLens
    if obj.Shape.distToShape(Part.Vertex(vertex))[0] < EPSILON:
<class 'RuntimeError'>: BRepExtrema_DistShapeShape failed
[/code]

**Comment by chbergmann** [comment]
fixed
